import { LevelDef } from '@/models/Level';

export const LevelConfigs: LevelDef[] = [
  // World 1: Enchanted Meadow
  // Each level 1-10 introduces a new mechanic
  {
    id: 1, world: 1, name: 'First Steps',
    spins: 5, movesPerSpin: 5,
    goals: [{ type: 'score', target: 500 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz'],
    hasBlockers: false,
    starThresholds: [500, 1000, 2000],
    intro: {
      title: 'Welcome!',
      description: 'Spin the reels to fill the board, then drag to swap adjacent gems and match 3 or more in a row!',
    },
  },
  {
    id: 2, world: 1, name: 'Cascade Valley',
    spins: 5, movesPerSpin: 5,
    goals: [{ type: 'cascades', target: 3 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion'],
    hasBlockers: false,
    starThresholds: [800, 1500, 3000],
    intro: {
      title: 'Cascade Chains!',
      description: 'When gems fall after a match, they can trigger chain reactions! Each cascade multiplies your score.',
    },
  },
  {
    id: 3, world: 1, name: 'Blast Off',
    spins: 5, movesPerSpin: 6,
    goals: [{ type: 'power_ups', target: 1 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: false,
    starThresholds: [1000, 2000, 4000],
    intro: {
      title: 'Blast Power-Up!',
      description: 'Match 4 in a line to create a Blast gem! Tap it to clear an entire row or column.',
    },
  },
  {
    id: 4, world: 1, name: 'Bomb Squad',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'power_ups', target: 2 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: false,
    starThresholds: [1200, 2500, 5000],
    intro: {
      title: 'Bomb Power-Up!',
      description: 'Match 4 in an L or T shape to create a Bomb! Tap it to clear a 3x3 area around it.',
    },
  },
  {
    id: 5, world: 1, name: 'Frozen Garden',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'clear_blockers', target: 4 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 4,
    starThresholds: [2000, 4000, 8000],
    intro: {
      title: 'Ice Blockers!',
      description: 'Ice tiles block your path! Clear matches next to them to break the ice. They cannot be swapped.',
    },
  },
  {
    id: 6, world: 1, name: 'Rainbow Bridge',
    spins: 6, movesPerSpin: 6,
    goals: [{ type: 'power_ups', target: 2 }, { type: 'score', target: 2000 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: false,
    starThresholds: [2500, 5000, 10000],
    intro: {
      title: 'Rainbow Power-Up!',
      description: 'Match 5 in a row to create a Rainbow gem! Tap it to clear all gems of one color from the board.',
    },
  },
  {
    id: 7, world: 1, name: 'Stone Keep',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 3 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 3,
    starThresholds: [3000, 6000, 12000],
    intro: {
      title: 'Stone Blockers!',
      description: 'Stone tiles are tougher — they need TWO adjacent matches to break! Plan your moves carefully.',
    },
  },
  {
    id: 8, world: 1, name: 'Gem Collector',
    spins: 6, movesPerSpin: 6,
    goals: [{ type: 'collect', target: 15, symbolId: 'ruby' }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy'],
    hasBlockers: false,
    starThresholds: [3000, 7000, 14000],
    intro: {
      title: 'Gem Collection!',
      description: 'Collect specific gems to complete the level. Focus your matches on the target gem!',
    },
  },
  {
    id: 9, world: 1, name: 'Last Chance',
    spins: 3, movesPerSpin: 7,
    goals: [{ type: 'score', target: 3000 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [3000, 6000, 12000],
    intro: {
      title: 'Limited Spins!',
      description: 'You have fewer spins this time. Every spin counts — plan your moves wisely and maximize each turn!',
    },
  },
  {
    id: 10, world: 1, name: 'Meadow Guardian',
    spins: 8, movesPerSpin: 6,
    goals: [{ type: 'score', target: 8000 }, { type: 'power_ups', target: 3 }, { type: 'clear_blockers', target: 4 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 4,
    starThresholds: [8000, 15000, 25000],
    intro: {
      title: "The Meadow Guardian!",
      description: "Everything you've learned comes together! Break blockers, use power-ups, and reach a massive score to save the meadow.",
    },
  },

  // World 2: Crystal Caverns
  {
    id: 11, world: 2, name: 'Into the Depths',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'score', target: 3000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy'],
    hasBlockers: false,
    starThresholds: [3000, 6000, 12000],
  },
  {
    id: 12, world: 2, name: 'Crystal Harvest',
    spins: 6, movesPerSpin: 6,
    goals: [{ type: 'collect', target: 20, symbolId: 'crystal' }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [4000, 8000, 15000],
  },
  {
    id: 13, world: 2, name: 'Frozen Path',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 5 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 5,
    starThresholds: [5000, 10000, 18000],
  },
  {
    id: 14, world: 2, name: 'Bat Colony',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'collect', target: 15, symbolId: 'bat' }, { type: 'score', target: 5000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [5000, 10000, 20000],
  },
  {
    id: 15, world: 2, name: 'Rainbow Cavern',
    spins: 7, movesPerSpin: 7,
    goals: [{ type: 'power_ups', target: 5 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [6000, 12000, 22000],
  },
  {
    id: 16, world: 2, name: 'Deep Freeze',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 10 }, { type: 'score', target: 6000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 10,
    starThresholds: [6000, 13000, 25000],
  },
  {
    id: 17, world: 2, name: 'Glowshroom Garden',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'collect', target: 25, symbolId: 'mushroom' }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [7000, 14000, 28000],
  },
  {
    id: 18, world: 2, name: 'Combo Crafter',
    spins: 8, movesPerSpin: 7,
    goals: [{ type: 'power_ups', target: 8 }, { type: 'cascades', target: 10 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [8000, 16000, 30000],
  },
  {
    id: 19, world: 2, name: 'Crystal Storm',
    spins: 8, movesPerSpin: 6,
    goals: [{ type: 'score', target: 15000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 5,
    starThresholds: [15000, 25000, 40000],
  },
  {
    id: 20, world: 2, name: 'Cavern Lord',
    spins: 10, movesPerSpin: 7,
    goals: [{ type: 'score', target: 20000 }, { type: 'power_ups', target: 10 }, { type: 'cascades', target: 15 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 6,
    starThresholds: [20000, 35000, 50000],
  },
];

export function getLevelConfig(id: number): LevelDef | undefined {
  return LevelConfigs.find(l => l.id === id);
}
