import { LevelDef } from '@/models/Level';

export const LevelConfigs: LevelDef[] = [
  // World 1: Enchanted Meadow
  {
    id: 1, world: 1, name: 'First Steps',
    spins: 5, movesPerSpin: 5,
    goals: [{ type: 'score', target: 500 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz'],
    hasBlockers: false,
    starThresholds: [500, 1000, 2000],
  },
  {
    id: 2, world: 1, name: 'Potion Brewer',
    spins: 5, movesPerSpin: 5,
    goals: [{ type: 'score', target: 800 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion'],
    hasBlockers: false,
    starThresholds: [800, 1500, 3000],
  },
  {
    id: 3, world: 1, name: 'Cascade Valley',
    spins: 5, movesPerSpin: 6,
    goals: [{ type: 'cascades', target: 3 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion'],
    hasBlockers: false,
    starThresholds: [1000, 2000, 4000],
  },
  {
    id: 4, world: 1, name: 'Scroll Seeker',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'collect', target: 3, symbolId: 'scatter' }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'scatter'],
    hasBlockers: false,
    starThresholds: [1200, 2500, 5000],
  },
  {
    id: 5, world: 1, name: 'Multiplier Grove',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'score', target: 2000 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [2000, 4000, 8000],
  },
  {
    id: 6, world: 1, name: 'Gem Collector',
    spins: 6, movesPerSpin: 6,
    goals: [{ type: 'collect', target: 15, symbolId: 'ruby' }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy'],
    hasBlockers: false,
    starThresholds: [2500, 5000, 10000],
  },
  {
    id: 7, world: 1, name: 'Power Play',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'power_ups', target: 3 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy', 'scatter'],
    hasBlockers: false,
    starThresholds: [3000, 6000, 12000],
  },
  {
    id: 8, world: 1, name: 'Wild Meadow',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'collect', target: 5, symbolId: 'roxy' }, { type: 'score', target: 3000 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [3000, 7000, 14000],
  },
  {
    id: 9, world: 1, name: 'Cascade Master',
    spins: 6, movesPerSpin: 7,
    goals: [{ type: 'cascades', target: 8 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [4000, 8000, 16000],
  },
  {
    id: 10, world: 1, name: 'Meadow Guardian',
    spins: 8, movesPerSpin: 6,
    goals: [{ type: 'score', target: 8000 }, { type: 'power_ups', target: 5 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz', 'potion', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [8000, 15000, 25000],
  },

  // World 2: Crystal Caverns
  {
    id: 11, world: 2, name: 'Into the Depths',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'score', target: 3000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy'],
    hasBlockers: false,
    starThresholds: [3000, 6000, 12000],
  },
  {
    id: 12, world: 2, name: 'Crystal Harvest',
    spins: 6, movesPerSpin: 6,
    goals: [{ type: 'collect', target: 20, symbolId: 'crystal' }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [4000, 8000, 15000],
  },
  {
    id: 13, world: 2, name: 'Frozen Path',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 5 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: true,
    starThresholds: [5000, 10000, 18000],
  },
  {
    id: 14, world: 2, name: 'Bat Colony',
    spins: 6, movesPerSpin: 5,
    goals: [{ type: 'collect', target: 15, symbolId: 'bat' }, { type: 'score', target: 5000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: false,
    starThresholds: [5000, 10000, 20000],
  },
  {
    id: 15, world: 2, name: 'Rainbow Cavern',
    spins: 7, movesPerSpin: 7,
    goals: [{ type: 'power_ups', target: 5 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [6000, 12000, 22000],
  },
  {
    id: 16, world: 2, name: 'Deep Freeze',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 10 }, { type: 'score', target: 6000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: true,
    starThresholds: [6000, 13000, 25000],
  },
  {
    id: 17, world: 2, name: 'Glowshroom Garden',
    spins: 7, movesPerSpin: 6,
    goals: [{ type: 'collect', target: 25, symbolId: 'mushroom' }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [7000, 14000, 28000],
  },
  {
    id: 18, world: 2, name: 'Combo Crafter',
    spins: 8, movesPerSpin: 7,
    goals: [{ type: 'power_ups', target: 8 }, { type: 'cascades', target: 10 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [8000, 16000, 30000],
  },
  {
    id: 19, world: 2, name: 'Crystal Storm',
    spins: 8, movesPerSpin: 6,
    goals: [{ type: 'score', target: 15000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    starThresholds: [15000, 25000, 40000],
  },
  {
    id: 20, world: 2, name: 'Cavern Lord',
    spins: 10, movesPerSpin: 7,
    goals: [{ type: 'score', target: 20000 }, { type: 'power_ups', target: 10 }, { type: 'cascades', target: 15 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    starThresholds: [20000, 35000, 50000],
  },
];

export function getLevelConfig(id: number): LevelDef | undefined {
  return LevelConfigs.find(l => l.id === id);
}
