import { LevelDef } from '@/models/Level';

export const LevelConfigs: LevelDef[] = [
  // ================================================================
  // WORLD 1: ENCHANTED MEADOW (Levels 1-10)
  // Feature ramp: match3 → cascades → blast → bomb → ice → rainbow → stone → collect → limited spins → boss
  // ================================================================

  {
    id: 1,
    world: 1,
    name: 'First Steps',
    spins: 5,
    movesPerSpin: 5,
    goals: [{ type: 'score', target: 500 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz'],
    hasBlockers: false,
    starThresholds: [500, 1000, 2000],
    intro: {
      title: 'Welcome!',
      description: 'Spin the reels to fill the board, then drag to swap adjacent gems and match 3 or more in a row!',
    },
  },
  {
    id: 2,
    world: 1,
    name: 'Cascade Valley',
    spins: 5,
    movesPerSpin: 5,
    goals: [{ type: 'cascades', target: 3 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst', 'topaz'],
    hasBlockers: false,
    starThresholds: [800, 1500, 3000],
    intro: {
      title: 'Cascade Chains!',
      description:
        'When gems fall after a match, they can trigger chain reactions! Each cascade multiplies your score.',
    },
  },
  {
    id: 3,
    world: 1,
    name: 'Blast Off',
    spins: 5,
    movesPerSpin: 6,
    goals: [{ type: 'power_ups', target: 1 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: false,
    starThresholds: [1000, 2000, 4000],
    intro: {
      title: 'Blast Power-Up!',
      description: 'Match 4 in a line to create a Blast gem! Tap it to clear an entire row or column.',
    },
  },
  {
    id: 4,
    world: 1,
    name: 'Bomb Squad',
    spins: 6,
    movesPerSpin: 5,
    goals: [{ type: 'power_ups', target: 2 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: false,
    starThresholds: [1200, 2500, 5000],
    intro: {
      title: 'Bomb Power-Up!',
      description: 'Match 4 in an L or T shape to create a Bomb! Tap it to clear a 3x3 area around it.',
    },
  },
  {
    id: 5,
    world: 1,
    name: 'Frozen Garden',
    spins: 6,
    movesPerSpin: 6,
    goals: [
      { type: 'clear_blockers', target: 4 },
      { type: 'score', target: 1500 },
    ],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 4,
    starThresholds: [2000, 4000, 8000],
    intro: {
      title: 'Ice Blockers!',
      description:
        'Ice tiles block your path! Match next to them to break the ice. Use power-ups to clear them faster!',
    },
  },
  {
    id: 6,
    world: 1,
    name: 'Rainbow Bridge',
    spins: 6,
    movesPerSpin: 6,
    goals: [
      { type: 'power_ups', target: 3 },
      { type: 'clear_blockers', target: 3 },
    ],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 3,
    starThresholds: [2500, 5000, 10000],
    intro: {
      title: 'Rainbow Power-Up!',
      description: 'Match 5 in a row to create a Rainbow gem! Tap it to clear all gems of one color from the board.',
    },
  },
  {
    id: 7,
    world: 1,
    name: 'Stone Keep',
    spins: 7,
    movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 5 }],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 3,
    blockerTypeSecondary: 'ice',
    blockerCountSecondary: 2,
    starThresholds: [3000, 6000, 12000],
    intro: {
      title: 'Stone Blockers!',
      description: 'Stone tiles are tougher — they need TWO adjacent matches to break! Use power-ups to help.',
    },
  },
  {
    id: 8,
    world: 1,
    name: 'Gem Collector',
    spins: 6,
    movesPerSpin: 6,
    goals: [
      { type: 'collect', target: 12, symbolId: 'ruby' },
      { type: 'clear_blockers', target: 3 },
    ],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 3,
    starThresholds: [3000, 7000, 14000],
    intro: {
      title: 'Gem Collection!',
      description: 'Collect specific gems to complete the level. Focus your matches on the target gem!',
    },
  },
  {
    id: 9,
    world: 1,
    name: 'Last Chance',
    spins: 3,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 3000 },
      { type: 'clear_blockers', target: 4 },
    ],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 2,
    blockerTypeSecondary: 'ice',
    blockerCountSecondary: 2,
    starThresholds: [3000, 6000, 12000],
    intro: {
      title: 'Limited Spins!',
      description: 'Only 3 spins but more moves each! Every spin counts — use power-ups to clear blockers fast!',
    },
  },
  {
    id: 10,
    world: 1,
    name: 'Meadow Guardian',
    spins: 8,
    movesPerSpin: 6,
    goals: [
      { type: 'score', target: 8000 },
      { type: 'power_ups', target: 3 },
      { type: 'clear_blockers', target: 6 },
    ],
    availableSymbolIds: ['ruby', 'emerald', 'sapphire', 'amethyst'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 3,
    blockerTypeSecondary: 'ice',
    blockerCountSecondary: 3,
    starThresholds: [8000, 15000, 25000],
    intro: {
      title: 'The Meadow Guardian!',
      description:
        "Everything you've learned comes together! Break ice and stone, create power-ups, and reach a massive score!",
    },
  },

  // ================================================================
  // WORLD 2: CRYSTAL CAVERNS (Levels 11-20) — Issue #16
  // Feature ramp: Wilds → Scatters → Multiplier Tiles → Chain Blockers → Timed Moves → Boss
  // ================================================================

  {
    id: 11,
    world: 2,
    name: 'Into the Depths',
    spins: 6,
    movesPerSpin: 5,
    goals: [{ type: 'score', target: 3000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy'],
    hasBlockers: false,
    starThresholds: [3000, 6000, 12000],
    intro: {
      title: 'Roxy is Wild!',
      description: 'She matches with any gem color. Look for her golden star to complete tricky matches!',
    },
  },
  {
    id: 12,
    world: 2,
    name: 'Crystal Harvest',
    spins: 6,
    movesPerSpin: 6,
    goals: [{ type: 'collect', target: 20, symbolId: 'crystal' }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy'],
    hasBlockers: false,
    starThresholds: [4000, 8000, 15000],
  },
  {
    id: 13,
    world: 2,
    name: 'Scroll Hunt',
    spins: 7,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 5000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: false,
    starThresholds: [5000, 10000, 18000],
    intro: {
      title: 'Magic Scrolls!',
      description:
        'Collect 3 Scatter Scrolls across your spins to earn a Bonus Spin! Watch the counter in the top bar.',
    },
  },
  {
    id: 14,
    world: 2,
    name: 'Bat Colony',
    spins: 6,
    movesPerSpin: 5,
    goals: [
      { type: 'collect', target: 15, symbolId: 'bat' },
      { type: 'score', target: 5000 },
    ],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: false,
    starThresholds: [5000, 10000, 20000],
  },
  {
    id: 15,
    world: 2,
    name: 'Multiplier Mines',
    spins: 7,
    movesPerSpin: 7,
    goals: [{ type: 'score', target: 8000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: false,
    starThresholds: [8000, 16000, 28000],
    multiplierTiles: [
      { row: 1, col: 1, multiplier: 2 },
      { row: 1, col: 3, multiplier: 2 },
      { row: 3, col: 1, multiplier: 3 },
      { row: 3, col: 3, multiplier: 2 },
    ],
    intro: {
      title: 'Multiplier Zones!',
      description: 'Gems matched on ×2 or ×3 tiles score double or triple. Plan your swaps to land matches on them!',
    },
  },
  {
    id: 16,
    world: 2,
    name: 'Deep Freeze',
    spins: 7,
    movesPerSpin: 6,
    goals: [
      { type: 'clear_blockers', target: 10 },
      { type: 'score', target: 6000 },
    ],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 10,
    multiplierTiles: [{ row: 2, col: 2, multiplier: 3 }],
    starThresholds: [6000, 13000, 25000],
  },
  {
    id: 17,
    world: 2,
    name: 'Chain Reaction',
    spins: 7,
    movesPerSpin: 6,
    goals: [{ type: 'clear_blockers', target: 6 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 2,
    chainBlockers: [
      {
        cells: [
          { row: 0, col: 2 },
          { row: 1, col: 2 },
          { row: 2, col: 2 },
        ],
      },
      {
        cells: [
          { row: 2, col: 0 },
          { row: 2, col: 1 },
        ],
      },
    ],
    starThresholds: [7000, 14000, 28000],
    intro: {
      title: 'Chained Blockers!',
      description: 'Breaking one weakens the next in the chain. Find the first link and work your way through!',
    },
  },
  {
    id: 18,
    world: 2,
    name: 'Chain Master',
    spins: 8,
    movesPerSpin: 7,
    goals: [
      { type: 'clear_blockers', target: 8 },
      { type: 'cascades', target: 10 },
    ],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 2,
    chainBlockers: [
      {
        cells: [
          { row: 0, col: 0 },
          { row: 0, col: 1 },
          { row: 0, col: 2 },
        ],
      },
      {
        cells: [
          { row: 4, col: 2 },
          { row: 4, col: 3 },
          { row: 4, col: 4 },
        ],
      },
    ],
    multiplierTiles: [{ row: 2, col: 2, multiplier: 2 }],
    starThresholds: [8000, 16000, 30000],
  },
  {
    id: 19,
    world: 2,
    name: 'Speed Run',
    spins: 8,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 15000 }],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 5,
    timedMoves: 8,
    multiplierTiles: [
      { row: 1, col: 1, multiplier: 2 },
      { row: 3, col: 3, multiplier: 2 },
    ],
    starThresholds: [15000, 25000, 40000],
    intro: {
      title: 'Speed Bonus!',
      description: 'Each move has a timer — the faster you swap, the bigger your score bonus. Watch the ring!',
    },
  },
  {
    id: 20,
    world: 2,
    name: 'Cavern Lord',
    spins: 10,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 20000 },
      { type: 'power_ups', target: 10 },
      { type: 'cascades', target: 15 },
    ],
    availableSymbolIds: ['crystal', 'mushroom', 'bat', 'amethyst', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 6,
    chainBlockers: [
      {
        cells: [
          { row: 0, col: 0 },
          { row: 1, col: 0 },
          { row: 2, col: 0 },
        ],
      },
    ],
    multiplierTiles: [{ row: 2, col: 2, multiplier: 3 }],
    timedMoves: 10,
    starThresholds: [20000, 35000, 50000],
    intro: {
      title: 'The Cavern Lord!',
      description: 'Use everything — Wilds, Scatters, Multipliers, and Chains to defeat the guardian!',
    },
  },

  // ================================================================
  // WORLD 3: VOLCANIC FORGE (Levels 21-30) — Issue #17 Part 1
  // Feature ramp: Lava → Locked Symbols → Combo Streaks → Conveyors → Boss
  // ================================================================

  {
    id: 21,
    world: 3,
    name: 'Lava Fields',
    spins: 7,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 5000 }],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy'],
    hasBlockers: false,
    lavaConfig: { initialCount: 3, spreadEveryNSpins: 3 },
    starThresholds: [5000, 10000, 20000],
    intro: {
      title: 'Lava Rising!',
      description: 'Lava tiles spread to empty neighbors each spin. Clear them with matches before they take over!',
    },
  },
  {
    id: 22,
    world: 3,
    name: 'Eruption',
    spins: 7,
    movesPerSpin: 6,
    goals: [
      { type: 'score', target: 7000 },
      { type: 'clear_blockers', target: 4 },
    ],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 4,
    lavaConfig: { initialCount: 4, spreadEveryNSpins: 3 },
    starThresholds: [7000, 14000, 25000],
  },
  {
    id: 23,
    world: 3,
    name: 'Lock & Key',
    spins: 7,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 6000 }],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'scatter'],
    hasBlockers: false,
    lockedSymbolCount: 4,
    starThresholds: [6000, 12000, 22000],
    intro: {
      title: 'Locked Gems!',
      description: 'Match adjacent gems to break the lock first, then match the freed gem. Two steps to clear!',
    },
  },
  {
    id: 24,
    world: 3,
    name: 'Forge Prison',
    spins: 8,
    movesPerSpin: 6,
    goals: [
      { type: 'score', target: 8000 },
      { type: 'power_ups', target: 4 },
    ],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 4,
    lockedSymbolCount: 3,
    lavaConfig: { initialCount: 2, spreadEveryNSpins: 4 },
    starThresholds: [8000, 16000, 28000],
  },
  {
    id: 25,
    world: 3,
    name: 'Hot Streak',
    spins: 7,
    movesPerSpin: 7,
    goals: [{ type: 'score', target: 10000 }],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'multiplier'],
    hasBlockers: false,
    comboStreak: true,
    starThresholds: [10000, 20000, 35000],
    intro: {
      title: 'Combo Streaks!',
      description:
        "Every successful swap builds your streak multiplier. Don't break the chain — one bad swap resets it!",
    },
  },
  {
    id: 26,
    world: 3,
    name: 'Streak Master',
    spins: 8,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 12000 },
      { type: 'cascades', target: 8 },
    ],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 4,
    comboStreak: true,
    lavaConfig: { initialCount: 2, spreadEveryNSpins: 4 },
    starThresholds: [12000, 22000, 38000],
  },
  {
    id: 27,
    world: 3,
    name: 'Conveyor Chaos',
    spins: 8,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 10000 }],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'scatter'],
    hasBlockers: false,
    conveyors: [
      { row: 1, direction: 'right' },
      { row: 3, direction: 'left' },
    ],
    starThresholds: [10000, 20000, 35000],
    intro: {
      title: 'Conveyor Rows!',
      description: 'Conveyor rows shift all gems one space each spin. Plan your swaps knowing the board will move!',
    },
  },
  {
    id: 28,
    world: 3,
    name: 'Factory Floor',
    spins: 8,
    movesPerSpin: 6,
    goals: [
      { type: 'score', target: 12000 },
      { type: 'power_ups', target: 6 },
    ],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 4,
    conveyors: [
      { row: 0, direction: 'right' },
      { row: 2, direction: 'left' },
      { row: 4, direction: 'right' },
    ],
    comboStreak: true,
    starThresholds: [12000, 24000, 40000],
  },
  {
    id: 29,
    world: 3,
    name: 'Forge Trial',
    spins: 8,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 15000 },
      { type: 'clear_blockers', target: 8 },
    ],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 5,
    blockerTypeSecondary: 'ice',
    blockerCountSecondary: 3,
    lavaConfig: { initialCount: 3, spreadEveryNSpins: 3 },
    conveyors: [{ row: 2, direction: 'right' }],
    comboStreak: true,
    starThresholds: [15000, 28000, 45000],
  },
  {
    id: 30,
    world: 3,
    name: 'Forge Master',
    spins: 10,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 25000 },
      { type: 'power_ups', target: 10 },
      { type: 'clear_blockers', target: 10 },
    ],
    availableSymbolIds: ['obsidian', 'magma', 'ember', 'slag', 'ruby', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 6,
    blockerTypeSecondary: 'ice',
    blockerCountSecondary: 4,
    lavaConfig: { initialCount: 4, spreadEveryNSpins: 2 },
    conveyors: [
      { row: 1, direction: 'right' },
      { row: 3, direction: 'left' },
    ],
    lockedSymbolCount: 3,
    comboStreak: true,
    starThresholds: [25000, 40000, 60000],
    intro: {
      title: 'The Forge Master!',
      description: "Lava, locks, and conveyors — master the volcano's fury to claim victory!",
    },
  },

  // ================================================================
  // WORLD 4: SUNKEN RUINS (Levels 31-40) — Issue #17 Part 2
  // Feature ramp: Cursed Symbols → Column Locks → Treasure Chests → Dual Collection → Boss
  // ================================================================

  {
    id: 31,
    world: 4,
    name: 'Sunken Entry',
    spins: 7,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 8000 }],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy'],
    hasBlockers: false,
    cursedConfig: { initialCount: 2, spreadAfterSpins: 2 },
    starThresholds: [8000, 16000, 28000],
    intro: {
      title: 'Cursed Gems!',
      description: 'If not cleared within 2 spins, cursed gems corrupt their neighbors. Purify them quickly!',
    },
  },
  {
    id: 32,
    world: 4,
    name: 'Cursed Depths',
    spins: 7,
    movesPerSpin: 6,
    goals: [
      { type: 'score', target: 10000 },
      { type: 'clear_blockers', target: 4 },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 4,
    cursedConfig: { initialCount: 3, spreadAfterSpins: 2 },
    starThresholds: [10000, 20000, 35000],
  },
  {
    id: 33,
    world: 4,
    name: 'Iron Gates',
    spins: 8,
    movesPerSpin: 6,
    goals: [{ type: 'score', target: 10000 }],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: false,
    columnLocks: { columns: [0, 1, 2, 3, 4], lockAfterSpins: 2 },
    starThresholds: [10000, 20000, 35000],
    intro: {
      title: 'Column Locks!',
      description: "After each spin, some columns lock — you can't swap gems in or out. Check which columns are free!",
    },
  },
  {
    id: 34,
    world: 4,
    name: 'Barred Passage',
    spins: 8,
    movesPerSpin: 6,
    goals: [
      { type: 'score', target: 12000 },
      { type: 'power_ups', target: 5 },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'multiplier'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 4,
    columnLocks: { columns: [0, 1, 2, 3, 4], lockAfterSpins: 2 },
    cursedConfig: { initialCount: 2, spreadAfterSpins: 3 },
    starThresholds: [12000, 24000, 40000],
  },
  {
    id: 35,
    world: 4,
    name: 'Treasure Hunt',
    spins: 8,
    movesPerSpin: 7,
    goals: [{ type: 'score', target: 12000 }],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'scatter'],
    hasBlockers: false,
    treasureChests: [
      { row: 1, col: 1, hitsNeeded: 3 },
      { row: 3, col: 3, hitsNeeded: 3 },
    ],
    starThresholds: [12000, 24000, 40000],
    intro: {
      title: 'Treasure Chests!',
      description: 'Match next to a chest 3 times to crack it open. Chests drop bonus coins and power-ups!',
    },
  },
  {
    id: 36,
    world: 4,
    name: 'Treasure Trove',
    spins: 8,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 15000 },
      { type: 'clear_blockers', target: 6 },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 6,
    treasureChests: [
      { row: 0, col: 0, hitsNeeded: 3 },
      { row: 0, col: 4, hitsNeeded: 3 },
      { row: 4, col: 2, hitsNeeded: 3 },
    ],
    starThresholds: [15000, 28000, 45000],
  },
  {
    id: 37,
    world: 4,
    name: 'Double Trouble',
    spins: 8,
    movesPerSpin: 6,
    goals: [
      { type: 'collect', target: 15, symbolId: 'pearl' },
      { type: 'collect', target: 15, symbolId: 'coral' },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy'],
    hasBlockers: false,
    starThresholds: [10000, 22000, 38000],
    intro: {
      title: 'Double Collection!',
      description: 'You need to gather two different gem types this level. Split your focus and plan carefully!',
    },
  },
  {
    id: 38,
    world: 4,
    name: 'Dual Depths',
    spins: 9,
    movesPerSpin: 6,
    goals: [
      { type: 'collect', target: 20, symbolId: 'shell' },
      { type: 'collect', target: 20, symbolId: 'trident' },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'ice',
    blockerCount: 4,
    cursedConfig: { initialCount: 2, spreadAfterSpins: 3 },
    starThresholds: [14000, 28000, 45000],
  },
  {
    id: 39,
    world: 4,
    name: 'Ruins Gauntlet',
    spins: 9,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 20000 },
      { type: 'clear_blockers', target: 10 },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 6,
    blockerTypeSecondary: 'ice',
    blockerCountSecondary: 4,
    cursedConfig: { initialCount: 3, spreadAfterSpins: 2 },
    columnLocks: { columns: [0, 2, 4], lockAfterSpins: 3 },
    treasureChests: [{ row: 2, col: 2, hitsNeeded: 3 }],
    starThresholds: [20000, 35000, 55000],
  },
  {
    id: 40,
    world: 4,
    name: 'Ruins Keeper',
    spins: 12,
    movesPerSpin: 7,
    goals: [
      { type: 'score', target: 30000 },
      { type: 'power_ups', target: 12 },
      { type: 'cascades', target: 20 },
    ],
    availableSymbolIds: ['pearl', 'coral', 'shell', 'trident', 'sapphire', 'roxy', 'scatter', 'multiplier'],
    hasBlockers: true,
    blockerType: 'stone',
    blockerCount: 8,
    cursedConfig: { initialCount: 4, spreadAfterSpins: 2 },
    columnLocks: { columns: [0, 1, 2, 3, 4], lockAfterSpins: 2 },
    treasureChests: [
      { row: 0, col: 0, hitsNeeded: 3 },
      { row: 4, col: 4, hitsNeeded: 3 },
    ],
    comboStreak: true,
    starThresholds: [30000, 50000, 75000],
    intro: {
      title: 'The Ruins Keeper!',
      description: 'Curses, column locks, and treasure — navigate every trap to escape the sunken ruins!',
    },
  },

  // ================================================================
  // WORLD 5: SKYWARD SPIRE (Levels 41-50) — Issue #18 Part 1
  // Feature ramp: Gravity Flip → Fog → Power-Up Combos → Thorns → Boss
  // ================================================================

  ...generateWorld5Levels(),

  // ================================================================
  // WORLD 6: SHADOW FOREST (Levels 51-60) — Issue #18 Part 2
  // Feature ramp: Shadows → Vines → Portals → Total Swap Budget → Boss
  // ================================================================

  ...generateWorld6Levels(),

  // ================================================================
  // WORLD 7: FROZEN WASTES (Levels 61-70) — Issue #19 Part 1
  // Feature ramp: Blizzard → Transformers → Chain Cascade Goal → Frozen Columns → Boss
  // ================================================================

  ...generateWorld7Levels(),

  // ================================================================
  // WORLD 8: DRAGON'S LAIR (Levels 71-80) — Issue #19 Part 2
  // Feature ramp: Fire Symbols → Dragon Eggs → Board Expansion → Power-Up Forge → Boss
  // ================================================================

  ...generateWorld8Levels(),

  // ================================================================
  // WORLD 9: ASTRAL REALM (Levels 81-90) — Issue #20 Part 1
  // Feature ramp: Phase Shifts → Mirror → Score Decay → Relics → Boss
  // ================================================================

  ...generateWorld9Levels(),

  // ================================================================
  // WORLD 10: ROXY'S TOWER (Levels 91-100) — Issue #20 Part 2
  // Feature ramp: Remixes → Prestige → Mega Power-Up → Cascade Mode → Gauntlet → Final Boss
  // ================================================================

  ...generateWorld10Levels(),
];

// ================================================================
// WORLD GENERATORS
// ================================================================

function generateWorld5Levels(): LevelDef[] {
  const w5base = ['cloud', 'lightning', 'wind', 'feather', 'amethyst', 'roxy'];
  return [
    {
      id: 41,
      world: 5,
      name: 'Gravity Shift',
      spins: 7,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 10000 }],
      availableSymbolIds: w5base,
      hasBlockers: false,
      gravityFlip: true,
      flipEveryNSpins: 2,
      starThresholds: [10000, 20000, 35000],
      intro: {
        title: 'Gravity Shift!',
        description: 'Some spins flip gravity — gems fall upward! Watch the arrow and plan for the new direction.',
      },
    },
    {
      id: 42,
      world: 5,
      name: 'Upside Down',
      spins: 7,
      movesPerSpin: 6,
      goals: [
        { type: 'score', target: 12000 },
        { type: 'cascades', target: 8 },
      ],
      availableSymbolIds: [...w5base, 'scatter'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 4,
      gravityFlip: true,
      flipEveryNSpins: 2,
      starThresholds: [12000, 24000, 40000],
    },
    {
      id: 43,
      world: 5,
      name: 'Fog Frontier',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 10000 }],
      availableSymbolIds: w5base,
      hasBlockers: false,
      fogCount: 8,
      starThresholds: [10000, 20000, 35000],
      intro: {
        title: 'Mysterious Fog!',
        description: "Some cells are hidden in fog — you can't see or swap them. Match adjacent gems to clear the fog!",
      },
    },
    {
      id: 44,
      world: 5,
      name: 'Hidden Depths',
      spins: 8,
      movesPerSpin: 6,
      goals: [
        { type: 'score', target: 14000 },
        { type: 'clear_blockers', target: 6 },
      ],
      availableSymbolIds: [...w5base, 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      fogCount: 10,
      gravityFlip: true,
      flipEveryNSpins: 3,
      starThresholds: [14000, 28000, 45000],
    },
    {
      id: 45,
      world: 5,
      name: 'Fusion Chamber',
      spins: 8,
      movesPerSpin: 7,
      goals: [{ type: 'power_ups', target: 6 }],
      availableSymbolIds: ['cloud', 'lightning', 'wind', 'roxy'],
      hasBlockers: false,
      powerUpCombos: true,
      starThresholds: [12000, 24000, 40000],
      intro: {
        title: 'Power-Up Fusion!',
        description: 'Swap two power-ups into each other to combine them into a devastating super attack!',
      },
    },
    {
      id: 46,
      world: 5,
      name: 'Combo Storm',
      spins: 8,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 18000 }],
      availableSymbolIds: ['cloud', 'lightning', 'wind', 'feather', 'roxy', 'scatter'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 6,
      powerUpCombos: true,
      gravityFlip: true,
      flipEveryNSpins: 3,
      starThresholds: [18000, 32000, 50000],
    },
    {
      id: 47,
      world: 5,
      name: 'Thorn Garden',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 12000 }],
      availableSymbolIds: [...w5base, 'scatter'],
      hasBlockers: false,
      thornCount: 4,
      starThresholds: [12000, 24000, 40000],
      intro: {
        title: 'Careful — Thorns!',
        description: 'Matching next to thorns damages your score. Use power-ups to clear them safely!',
      },
    },
    {
      id: 48,
      world: 5,
      name: 'Spire Ascent',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 18000 },
        { type: 'power_ups', target: 8 },
      ],
      availableSymbolIds: [...w5base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 4,
      thornCount: 3,
      fogCount: 5,
      powerUpCombos: true,
      starThresholds: [18000, 32000, 52000],
    },
    {
      id: 49,
      world: 5,
      name: 'Spire Trial',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 22000 },
        { type: 'clear_blockers', target: 8 },
      ],
      availableSymbolIds: [...w5base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      thornCount: 4,
      gravityFlip: true,
      flipEveryNSpins: 2,
      powerUpCombos: true,
      comboStreak: true,
      starThresholds: [22000, 38000, 58000],
    },
    {
      id: 50,
      world: 5,
      name: 'Spire Sentinel',
      spins: 12,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 35000 },
        { type: 'power_ups', target: 12 },
        { type: 'cascades', target: 20 },
      ],
      availableSymbolIds: [...w5base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      blockerTypeSecondary: 'ice',
      blockerCountSecondary: 4,
      gravityFlip: true,
      flipEveryNSpins: 2,
      fogCount: 6,
      thornCount: 4,
      powerUpCombos: true,
      comboStreak: true,
      starThresholds: [35000, 55000, 80000],
      intro: {
        title: 'The Spire Sentinel!',
        description: 'Shifting gravity, hidden fog, and deadly thorns — combine your power-ups to break through!',
      },
    },
  ];
}

function generateWorld6Levels(): LevelDef[] {
  const w6base = ['moonstone', 'nightbloom', 'shadowgem', 'spore', 'amethyst', 'roxy'];
  return [
    {
      id: 51,
      world: 6,
      name: 'Shadow Veil',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 12000 }],
      availableSymbolIds: w6base,
      hasBlockers: false,
      shadowCount: 10,
      starThresholds: [12000, 24000, 40000],
      intro: {
        title: 'Shadow Gems!',
        description: 'Some gems hide their true colors. Swap to peek — remember what you see!',
      },
    },
    {
      id: 52,
      world: 6,
      name: 'Memory Test',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'collect', target: 20, symbolId: 'moonstone' }],
      availableSymbolIds: w6base,
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 4,
      shadowCount: 12,
      starThresholds: [14000, 28000, 45000],
    },
    {
      id: 53,
      world: 6,
      name: 'Overgrown',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 14000 }],
      availableSymbolIds: [...w6base, 'scatter'],
      hasBlockers: false,
      vineConfig: { initialCount: 4, growthPerSpin: 2, growFromEdges: true },
      starThresholds: [14000, 28000, 45000],
      intro: {
        title: 'Vines Creeping!',
        description: 'They grow from edges each spin, blocking your moves. Match next to them to cut them back!',
      },
    },
    {
      id: 54,
      world: 6,
      name: 'Jungle Floor',
      spins: 8,
      movesPerSpin: 6,
      goals: [
        { type: 'score', target: 16000 },
        { type: 'clear_blockers', target: 6 },
      ],
      availableSymbolIds: [...w6base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      vineConfig: { initialCount: 4, growthPerSpin: 2, growFromEdges: true },
      shadowCount: 6,
      starThresholds: [16000, 30000, 48000],
    },
    {
      id: 55,
      world: 6,
      name: 'Portal Paths',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'cascades', target: 12 }],
      availableSymbolIds: w6base,
      hasBlockers: false,
      portals: [
        { id: 'A', cell1: { row: 0, col: 0 }, cell2: { row: 4, col: 4 } },
        { id: 'B', cell1: { row: 0, col: 4 }, cell2: { row: 4, col: 0 } },
      ],
      starThresholds: [14000, 28000, 45000],
      intro: {
        title: 'Magic Portals!',
        description: 'Paired portals are connected — gems that fall into one teleport out the other!',
      },
    },
    {
      id: 56,
      world: 6,
      name: 'Portal Maze',
      spins: 9,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 18000 }],
      availableSymbolIds: [...w6base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 6,
      portals: [
        { id: 'A', cell1: { row: 0, col: 2 }, cell2: { row: 4, col: 2 } },
        { id: 'B', cell1: { row: 2, col: 0 }, cell2: { row: 2, col: 4 } },
      ],
      vineConfig: { initialCount: 3, growthPerSpin: 1, growFromEdges: true },
      starThresholds: [18000, 32000, 50000],
    },
    {
      id: 57,
      world: 6,
      name: 'Swap Budget',
      spins: 5,
      movesPerSpin: 99,
      goals: [{ type: 'score', target: 15000 }],
      availableSymbolIds: w6base,
      hasBlockers: false,
      totalSwapBudget: 20,
      starThresholds: [15000, 28000, 45000],
      intro: {
        title: 'Swap Budget!',
        description: 'This level gives you a total number of swaps across ALL spins. Make every move count!',
      },
    },
    {
      id: 58,
      world: 6,
      name: 'Budget Crunch',
      spins: 5,
      movesPerSpin: 99,
      goals: [
        { type: 'score', target: 20000 },
        { type: 'power_ups', target: 6 },
      ],
      availableSymbolIds: [...w6base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 4,
      totalSwapBudget: 25,
      vineConfig: { initialCount: 3, growthPerSpin: 1, growFromEdges: true },
      starThresholds: [20000, 35000, 55000],
    },
    {
      id: 59,
      world: 6,
      name: 'Forest Trial',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 25000 },
        { type: 'clear_blockers', target: 10 },
      ],
      availableSymbolIds: [...w6base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      blockerTypeSecondary: 'ice',
      blockerCountSecondary: 4,
      shadowCount: 8,
      vineConfig: { initialCount: 4, growthPerSpin: 2, growFromEdges: true },
      portals: [{ id: 'A', cell1: { row: 0, col: 0 }, cell2: { row: 4, col: 4 } }],
      powerUpCombos: true,
      starThresholds: [25000, 42000, 65000],
    },
    {
      id: 60,
      world: 6,
      name: 'Forest Shade',
      spins: 12,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 40000 },
        { type: 'power_ups', target: 15 },
        { type: 'cascades', target: 25 },
      ],
      availableSymbolIds: [...w6base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 10,
      shadowCount: 10,
      vineConfig: { initialCount: 5, growthPerSpin: 3, growFromEdges: true },
      portals: [
        { id: 'A', cell1: { row: 0, col: 0 }, cell2: { row: 4, col: 4 } },
        { id: 'B', cell1: { row: 0, col: 4 }, cell2: { row: 4, col: 0 } },
      ],
      powerUpCombos: true,
      comboStreak: true,
      starThresholds: [40000, 60000, 90000],
      intro: {
        title: 'The Forest Shade!',
        description: 'Shadows, vines, and portals twist the board. Use every trick to survive the darkness!',
      },
    },
  ];
}

function generateWorld7Levels(): LevelDef[] {
  const w7base = ['icicle', 'snowflake', 'froststone', 'aurora', 'sapphire', 'roxy'];
  return [
    {
      id: 61,
      world: 7,
      name: 'Blizzard Warning',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 15000 }],
      availableSymbolIds: w7base,
      hasBlockers: false,
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 3 },
      starThresholds: [15000, 28000, 45000],
      intro: {
        title: 'Blizzard Incoming!',
        description: 'Every few spins, a storm freezes random cells. Watch the snowflake counter and clear ice fast!',
      },
    },
    {
      id: 62,
      world: 7,
      name: 'Whiteout',
      spins: 8,
      movesPerSpin: 6,
      goals: [
        { type: 'clear_blockers', target: 12 },
        { type: 'score', target: 12000 },
      ],
      availableSymbolIds: [...w7base, 'scatter'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 4,
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 4 },
      starThresholds: [12000, 24000, 40000],
    },
    {
      id: 63,
      world: 7,
      name: 'Alchemy Lab',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 15000 }],
      availableSymbolIds: w7base,
      hasBlockers: false,
      transformers: [
        { row: 2, col: 0, transformsTo: 'aurora' },
        { row: 2, col: 4, transformsTo: 'icicle' },
      ],
      starThresholds: [15000, 28000, 45000],
      intro: {
        title: 'Alchemy Tiles!',
        description: 'Special cells transform any gem that lands on them. Use them to set up matches!',
      },
    },
    {
      id: 64,
      world: 7,
      name: 'Transmutation',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'collect', target: 25, symbolId: 'aurora' }],
      availableSymbolIds: [...w7base, 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 4,
      transformers: [
        { row: 1, col: 2, transformsTo: 'aurora' },
        { row: 3, col: 2, transformsTo: 'aurora' },
      ],
      blizzardConfig: { freezeEveryNSpins: 3, cellsToFreeze: 2 },
      starThresholds: [18000, 32000, 50000],
    },
    {
      id: 65,
      world: 7,
      name: 'Chain Master',
      spins: 8,
      movesPerSpin: 7,
      goals: [{ type: 'chain_cascade', target: 5 }],
      availableSymbolIds: ['icicle', 'snowflake', 'froststone', 'roxy'],
      hasBlockers: false,
      starThresholds: [15000, 30000, 50000],
      intro: {
        title: 'Chain Master!',
        description: 'This level needs long cascade chains. Set up the board so one match triggers a massive reaction!',
      },
    },
    {
      id: 66,
      world: 7,
      name: 'Avalanche',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'chain_cascade', target: 4 },
        { type: 'score', target: 20000 },
      ],
      availableSymbolIds: [...w7base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 6,
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 3 },
      transformers: [{ row: 2, col: 2, transformsTo: 'icicle' }],
      starThresholds: [20000, 36000, 55000],
    },
    {
      id: 67,
      world: 7,
      name: 'Ice Pillars',
      spins: 9,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 18000 }],
      availableSymbolIds: w7base,
      hasBlockers: false,
      frozenColumns: [1, 3],
      starThresholds: [18000, 32000, 50000],
      intro: {
        title: 'Frozen Columns!',
        description: 'Entire columns freeze solid. Match in neighboring columns to thaw them out!',
      },
    },
    {
      id: 68,
      world: 7,
      name: 'Permafrost',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 22000 },
        { type: 'power_ups', target: 8 },
      ],
      availableSymbolIds: [...w7base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 4,
      frozenColumns: [0, 4],
      blizzardConfig: { freezeEveryNSpins: 3, cellsToFreeze: 3 },
      powerUpCombos: true,
      starThresholds: [22000, 38000, 58000],
    },
    {
      id: 69,
      world: 7,
      name: 'Frost Trial',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 28000 },
        { type: 'clear_blockers', target: 15 },
      ],
      availableSymbolIds: [...w7base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      blockerTypeSecondary: 'ice',
      blockerCountSecondary: 4,
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 4 },
      frozenColumns: [2],
      transformers: [{ row: 0, col: 2, transformsTo: 'aurora' }],
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [28000, 45000, 70000],
    },
    {
      id: 70,
      world: 7,
      name: 'Frost Giant',
      spins: 12,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 45000 },
        { type: 'power_ups', target: 15 },
        { type: 'clear_blockers', target: 20 },
      ],
      availableSymbolIds: [...w7base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 10,
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 5 },
      frozenColumns: [1, 3],
      transformers: [
        { row: 2, col: 0, transformsTo: 'icicle' },
        { row: 2, col: 4, transformsTo: 'aurora' },
      ],
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [45000, 70000, 100000],
      intro: {
        title: 'The Frost Giant!',
        description: 'Blizzards rage, columns freeze, and alchemy twists. Survive the frozen wastes!',
      },
    },
  ];
}

function generateWorld8Levels(): LevelDef[] {
  const w8base = ['firegem', 'dragonfang', 'dragonscale', 'molten', 'ruby', 'roxy'];
  return [
    {
      id: 71,
      world: 8,
      name: 'Fire & Ice',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'clear_blockers', target: 8 }],
      availableSymbolIds: w8base,
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 8,
      fireSymbols: true,
      starThresholds: [15000, 28000, 45000],
      intro: {
        title: 'Fire Gems!',
        description: 'Match fire gems to unleash flames that melt ice and stone! Fight fire against the frost!',
      },
    },
    {
      id: 72,
      world: 8,
      name: 'Meltdown',
      spins: 8,
      movesPerSpin: 6,
      goals: [
        { type: 'clear_blockers', target: 12 },
        { type: 'score', target: 18000 },
      ],
      availableSymbolIds: [...w8base, 'scatter'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      blockerTypeSecondary: 'ice',
      blockerCountSecondary: 4,
      fireSymbols: true,
      starThresholds: [18000, 32000, 50000],
    },
    {
      id: 73,
      world: 8,
      name: 'Nest Guardian',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 20000 }],
      availableSymbolIds: w8base,
      hasBlockers: false,
      dragonEggs: [{ row: 2, col: 2, spinsToHatch: 3 }],
      starThresholds: [20000, 35000, 55000],
      intro: {
        title: 'Dragon Egg!',
        description: "Protect the egg for 3 spins and it hatches for a massive bonus. Don't destroy it early!",
      },
    },
    {
      id: 74,
      world: 8,
      name: 'Dragon Nursery',
      spins: 9,
      movesPerSpin: 6,
      goals: [
        { type: 'score', target: 25000 },
        { type: 'power_ups', target: 8 },
      ],
      availableSymbolIds: [...w8base, 'multiplier'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 4,
      dragonEggs: [
        { row: 1, col: 1, spinsToHatch: 3 },
        { row: 3, col: 3, spinsToHatch: 3 },
      ],
      fireSymbols: true,
      starThresholds: [25000, 42000, 65000],
    },
    {
      id: 75,
      world: 8,
      name: 'Wider World',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 20000 }],
      availableSymbolIds: [...w8base, 'scatter'],
      hasBlockers: false,
      gridSize: { rows: 5, cols: 6 },
      starThresholds: [20000, 35000, 55000],
      intro: {
        title: 'Bigger Board!',
        description: 'The grid expanded to 6 columns. More gems, more matches, more chaos!',
      },
    },
    {
      id: 76,
      world: 8,
      name: 'Dragon Arena',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 25000 },
        { type: 'clear_blockers', target: 8 },
      ],
      availableSymbolIds: [...w8base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      gridSize: { rows: 5, cols: 6 },
      fireSymbols: true,
      dragonEggs: [{ row: 2, col: 3, spinsToHatch: 3 }],
      starThresholds: [25000, 42000, 65000],
    },
    {
      id: 77,
      world: 8,
      name: 'Forge Shop',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 22000 }],
      availableSymbolIds: w8base,
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      powerUpForge: true,
      starThresholds: [22000, 38000, 58000],
      intro: {
        title: 'Power-Up Forge!',
        description: 'Before spinning, spend coins to place a power-up on the board. Choose wisely!',
      },
    },
    {
      id: 78,
      world: 8,
      name: 'Arsenal',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 28000 },
        { type: 'power_ups', target: 10 },
      ],
      availableSymbolIds: [...w8base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      blockerTypeSecondary: 'ice',
      blockerCountSecondary: 4,
      powerUpForge: true,
      fireSymbols: true,
      powerUpCombos: true,
      starThresholds: [28000, 48000, 72000],
    },
    {
      id: 79,
      world: 8,
      name: 'Dragon Trial',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 35000 },
        { type: 'clear_blockers', target: 15 },
      ],
      availableSymbolIds: [...w8base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 10,
      gridSize: { rows: 5, cols: 6 },
      fireSymbols: true,
      powerUpForge: true,
      powerUpCombos: true,
      blizzardConfig: { freezeEveryNSpins: 3, cellsToFreeze: 3 },
      comboStreak: true,
      starThresholds: [35000, 55000, 85000],
    },
    {
      id: 80,
      world: 8,
      name: 'Dragon King',
      spins: 14,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 60000 },
        { type: 'power_ups', target: 20 },
        { type: 'cascades', target: 30 },
      ],
      availableSymbolIds: [...w8base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 12,
      gridSize: { rows: 5, cols: 6 },
      fireSymbols: true,
      powerUpForge: true,
      powerUpCombos: true,
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 4 },
      dragonEggs: [{ row: 1, col: 3, spinsToHatch: 3 }],
      comboStreak: true,
      starThresholds: [60000, 90000, 130000],
      intro: {
        title: 'The Dragon King!',
        description: 'Fire and ice collide in a multi-phase battle. Only the strongest strategist will prevail!',
      },
    },
  ];
}

function generateWorld9Levels(): LevelDef[] {
  const w9base = ['stardust', 'nebula', 'comet', 'void', 'amethyst', 'roxy'];
  return [
    {
      id: 81,
      world: 9,
      name: 'Phase Rift',
      spins: 8,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 20000 }],
      availableSymbolIds: w9base,
      hasBlockers: false,
      phaseShifts: [
        { phase: 0, activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })) },
        {
          phase: 1,
          activeCells: [
            { row: 0, col: 1 },
            { row: 0, col: 2 },
            { row: 0, col: 3 },
            { row: 1, col: 0 },
            { row: 1, col: 1 },
            { row: 1, col: 2 },
            { row: 1, col: 3 },
            { row: 1, col: 4 },
            { row: 2, col: 0 },
            { row: 2, col: 1 },
            { row: 2, col: 2 },
            { row: 2, col: 3 },
            { row: 2, col: 4 },
            { row: 3, col: 0 },
            { row: 3, col: 1 },
            { row: 3, col: 2 },
            { row: 3, col: 3 },
            { row: 3, col: 4 },
            { row: 4, col: 1 },
            { row: 4, col: 2 },
            { row: 4, col: 3 },
          ],
        },
      ],
      starThresholds: [20000, 35000, 55000],
      intro: {
        title: 'Phase Shifts!',
        description: 'Cells appear and disappear mid-level, changing the board shape. Watch for the purple shimmer!',
      },
    },
    {
      id: 82,
      world: 9,
      name: 'Shifting Sands',
      spins: 9,
      movesPerSpin: 6,
      goals: [
        { type: 'score', target: 25000 },
        { type: 'cascades', target: 12 },
      ],
      availableSymbolIds: [...w9base, 'scatter'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 4,
      phaseShifts: [
        { phase: 0, activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })) },
        {
          phase: 1,
          activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })).filter(
            (c) => c.col >= 1 && c.col <= 3,
          ),
        },
        {
          phase: 2,
          activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })).filter(
            (c) => c.row >= 1 && c.row <= 3,
          ),
        },
      ],
      starThresholds: [25000, 42000, 65000],
    },
    {
      id: 83,
      world: 9,
      name: 'Mirror Realm',
      spins: 8,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 25000 }],
      availableSymbolIds: w9base,
      hasBlockers: false,
      mirrorAxis: 'vertical',
      starThresholds: [25000, 42000, 65000],
      intro: {
        title: 'Mirror Magic!',
        description: 'The board is split by a mirror — matches on one side reflect on the other! Double score!',
      },
    },
    {
      id: 84,
      world: 9,
      name: 'Reflection Pool',
      spins: 9,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 30000 },
        { type: 'power_ups', target: 10 },
      ],
      availableSymbolIds: [...w9base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 6,
      mirrorAxis: 'horizontal',
      powerUpCombos: true,
      starThresholds: [30000, 50000, 75000],
    },
    {
      id: 85,
      world: 9,
      name: 'Decay Begins',
      spins: 8,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 20000 }],
      availableSymbolIds: w9base,
      hasBlockers: false,
      scoreDecay: { ratePerSecond: 10, maxRate: 50 },
      starThresholds: [20000, 35000, 55000],
      intro: {
        title: 'Score Decay!',
        description: 'Your score slowly drains between moves. Play fast to minimize the loss!',
      },
    },
    {
      id: 86,
      world: 9,
      name: 'Racing Time',
      spins: 8,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 28000 }],
      availableSymbolIds: [...w9base, 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      scoreDecay: { ratePerSecond: 15, maxRate: 75 },
      mirrorAxis: 'vertical',
      comboStreak: true,
      starThresholds: [28000, 48000, 72000],
    },
    {
      id: 87,
      world: 9,
      name: 'Relic Seeker',
      spins: 10,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 25000 }],
      availableSymbolIds: w9base,
      hasBlockers: false,
      relicPieces: [
        { piece: 1, row: 0, col: 0 },
        { piece: 2, row: 0, col: 4 },
        { piece: 3, row: 4, col: 0 },
        { piece: 4, row: 4, col: 4 },
      ],
      starThresholds: [25000, 45000, 70000],
      intro: {
        title: 'Ancient Relic!',
        description: 'Four pieces hidden in corners. Collect all four to assemble the relic for a massive bonus!',
      },
    },
    {
      id: 88,
      world: 9,
      name: 'Relic Quest',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 35000 },
        { type: 'clear_blockers', target: 10 },
      ],
      availableSymbolIds: [...w9base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 10,
      relicPieces: [
        { piece: 1, row: 0, col: 0 },
        { piece: 2, row: 0, col: 4 },
        { piece: 3, row: 4, col: 0 },
        { piece: 4, row: 4, col: 4 },
      ],
      phaseShifts: [
        { phase: 0, activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })) },
        {
          phase: 1,
          activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })).filter(
            (c) => !(c.row === 2 && c.col === 2),
          ),
        },
      ],
      scoreDecay: { ratePerSecond: 10, maxRate: 50 },
      powerUpCombos: true,
      starThresholds: [35000, 55000, 85000],
    },
    {
      id: 89,
      world: 9,
      name: 'Astral Trial',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 40000 },
        { type: 'power_ups', target: 12 },
      ],
      availableSymbolIds: [...w9base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      phaseShifts: [
        { phase: 0, activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })) },
        {
          phase: 1,
          activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })).filter(
            (c) => c.row !== 0 && c.row !== 4,
          ),
        },
      ],
      mirrorAxis: 'vertical',
      scoreDecay: { ratePerSecond: 12, maxRate: 60 },
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [40000, 65000, 95000],
    },
    {
      id: 90,
      world: 9,
      name: 'Astral Warden',
      spins: 14,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 70000 },
        { type: 'power_ups', target: 20 },
        { type: 'cascades', target: 30 },
      ],
      availableSymbolIds: [...w9base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 12,
      phaseShifts: [
        { phase: 0, activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })) },
        {
          phase: 1,
          activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })).filter(
            (c) => c.col >= 1 && c.col <= 3,
          ),
        },
      ],
      mirrorAxis: 'vertical',
      scoreDecay: { ratePerSecond: 15, maxRate: 75 },
      relicPieces: [
        { piece: 1, row: 0, col: 0 },
        { piece: 2, row: 0, col: 4 },
        { piece: 3, row: 4, col: 0 },
        { piece: 4, row: 4, col: 4 },
      ],
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [70000, 100000, 150000],
      intro: {
        title: 'The Astral Warden!',
        description: 'Shifting phases, mirrored dimensions, and decaying time — only true mastery will prevail!',
      },
    },
  ];
}

function generateWorld10Levels(): LevelDef[] {
  const w10base = ['arcane', 'runic', 'enchanted', 'tower', 'amethyst', 'roxy'];
  return [
    {
      id: 91,
      world: 10,
      name: 'Lava Blizzard',
      spins: 10,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 35000 }],
      availableSymbolIds: [...w10base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      isRemix: true,
      remixName: 'Lava Blizzard',
      lavaConfig: { initialCount: 3, spreadEveryNSpins: 3 },
      blizzardConfig: { freezeEveryNSpins: 2, cellsToFreeze: 3 },
      fireSymbols: true,
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [35000, 55000, 85000],
      intro: {
        title: "Roxy's Tower — Floor 1",
        description: 'Lava Blizzard! Fire and ice clash. Every floor remixes the deadliest mechanics!',
      },
    },
    {
      id: 92,
      world: 10,
      name: 'Shadow Portals',
      spins: 10,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 40000 }],
      availableSymbolIds: [...w10base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      isRemix: true,
      remixName: 'Shadow Portals',
      shadowCount: 12,
      portals: [
        { id: 'A', cell1: { row: 0, col: 0 }, cell2: { row: 4, col: 4 } },
        { id: 'B', cell1: { row: 0, col: 4 }, cell2: { row: 4, col: 0 } },
      ],
      vineConfig: { initialCount: 4, growthPerSpin: 2, growFromEdges: true },
      gravityFlip: true,
      flipEveryNSpins: 2,
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [40000, 65000, 95000],
      intro: {
        title: "Roxy's Tower — Floor 2",
        description: 'Shadow Portals! Darkness and teleportation twist every move!',
      },
    },
    {
      id: 93,
      world: 10,
      name: 'Prestige Hall',
      spins: 10,
      movesPerSpin: 7,
      goals: [{ type: 'score', target: 45000 }],
      availableSymbolIds: [...w10base, 'prestige', 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      prestigeSymbols: true,
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [45000, 70000, 105000],
      intro: {
        title: 'Prestige Gems!',
        description: 'Ultra-rare prismatic diamonds worth 5× normal score. Treasure every one!',
      },
    },
    {
      id: 94,
      world: 10,
      name: 'Diamond Mine',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 50000 },
        { type: 'collect', target: 5, symbolId: 'prestige' },
      ],
      availableSymbolIds: [...w10base, 'prestige', 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 8,
      prestigeSymbols: true,
      mirrorAxis: 'vertical',
      scoreDecay: { ratePerSecond: 10, maxRate: 50 },
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [50000, 80000, 120000],
    },
    {
      id: 95,
      world: 10,
      name: 'Mega Fusion',
      spins: 10,
      movesPerSpin: 7,
      goals: [{ type: 'power_ups', target: 15 }],
      availableSymbolIds: ['arcane', 'runic', 'enchanted', 'roxy'],
      hasBlockers: false,
      megaPowerUp: true,
      powerUpCombos: true,
      starThresholds: [40000, 65000, 100000],
      intro: {
        title: 'MEGA Power-Up!',
        description: 'Get 3 power-ups in a triangle to fuse them. Tap to clear half the board!',
      },
    },
    {
      id: 96,
      world: 10,
      name: 'Mega Arsenal',
      spins: 10,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 55000 },
        { type: 'power_ups', target: 15 },
      ],
      availableSymbolIds: [...w10base, 'prestige', 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 10,
      megaPowerUp: true,
      powerUpCombos: true,
      powerUpForge: true,
      comboStreak: true,
      starThresholds: [55000, 85000, 130000],
    },
    {
      id: 97,
      world: 10,
      name: 'Cascade Flow',
      spins: 8,
      movesPerSpin: 0,
      goals: [{ type: 'score', target: 40000 }],
      availableSymbolIds: w10base,
      hasBlockers: false,
      cascadeOnlyMode: true,
      starThresholds: [40000, 65000, 100000],
      intro: {
        title: 'Cascade Mode!',
        description: 'No swaps — your score comes purely from chain reactions. Choose when to spin!',
      },
    },
    {
      id: 98,
      world: 10,
      name: 'Chain Lightning',
      spins: 10,
      movesPerSpin: 0,
      goals: [{ type: 'score', target: 60000 }],
      availableSymbolIds: [...w10base, 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'ice',
      blockerCount: 4,
      cascadeOnlyMode: true,
      starThresholds: [60000, 90000, 140000],
    },
    {
      id: 99,
      world: 10,
      name: 'The Gauntlet',
      spins: 9,
      movesPerSpin: 6,
      goals: [{ type: 'score', target: 50000 }],
      availableSymbolIds: [...w10base, 'prestige', 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 6,
      gauntlet: [
        { rows: 3, cols: 3 },
        { rows: 4, cols: 4 },
        { rows: 5, cols: 5 },
      ],
      comboStreak: true,
      powerUpCombos: true,
      starThresholds: [50000, 80000, 120000],
      intro: {
        title: 'The Gauntlet!',
        description: 'Three boards, three challenges, one combined score. Start small and survive!',
      },
    },
    {
      id: 100,
      world: 10,
      name: "Roxy's Tower",
      spins: 20,
      movesPerSpin: 7,
      goals: [
        { type: 'score', target: 100000 },
        { type: 'power_ups', target: 25 },
        { type: 'cascades', target: 50 },
      ],
      availableSymbolIds: [...w10base, 'prestige', 'scatter', 'multiplier'],
      hasBlockers: true,
      blockerType: 'stone',
      blockerCount: 15,
      megaPowerUp: true,
      powerUpCombos: true,
      powerUpForge: true,
      comboStreak: true,
      prestigeSymbols: true,
      blizzardConfig: { freezeEveryNSpins: 3, cellsToFreeze: 3 },
      fireSymbols: true,
      phaseShifts: [
        { phase: 0, activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })) },
        {
          phase: 1,
          activeCells: Array.from({ length: 25 }, (_, i) => ({ row: Math.floor(i / 5), col: i % 5 })).filter(
            (c) => c.col >= 1 && c.col <= 3,
          ),
        },
      ],
      mirrorAxis: 'vertical',
      relicPieces: [
        { piece: 1, row: 0, col: 0 },
        { piece: 2, row: 0, col: 4 },
        { piece: 3, row: 4, col: 0 },
        { piece: 4, row: 4, col: 4 },
      ],
      starThresholds: [100000, 150000, 250000],
      intro: {
        title: 'The Final Floor!',
        description:
          "Everything you've mastered leads here. Roxy is counting on you — conquer the tower and become a legend!",
      },
    },
  ];
}

export function getLevelConfig(id: number): LevelDef | undefined {
  return LevelConfigs.find((l) => l.id === id);
}
